#!/bin/bash source-this-script
[ "$BASH_VERSION" ] || return

_timer()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    local -r OPTS="-@ -@@ -+ -++ -d -f -h -p -P -PP -a -n -t -v -vv -V -x"
    local -r COMMANDS="\
        add a addto addm append app archive command del  \
        rm depri dp do help list ls listaddons listall lsa listcon  \
        lsc listfile lf listpri lsp listproj lsprj move \
        mv prepend prep pri p replace report shorthelp   happy"

    local _timer_sh=${_timer_sh:-timer.sh}
    local completions
    if [ $COMP_CWORD -eq 1 ]; then
        completions="$COMMANDS $(eval TIMERTXT_VERBOSE=0 $_timer_sh command listaddons) $OPTS"
    elif [[ $COMP_CWORD -gt 2 && ( \
        "${COMP_WORDS[COMP_CWORD-2]}" =~ ^(move|mv)$ || \
        "${COMP_WORDS[COMP_CWORD-3]}" =~ ^(move|mv)$ ) ]]; then
        # "move ITEM# DEST [SRC]" has file arguments on positions 2 and 3.
        completions=$(eval TIMERTXT_VERBOSE=0 $_timer_sh command listfile)
    else
        case "$prev" in
            command)
                completions=$COMMANDS;;
            addto|listfile|lf)
                completions=$(eval TIMERTXT_VERBOSE=0 $_timer_sh command listfile);;
            -*) completions="$COMMANDS $(eval TIMERTXT_VERBOSE=0 $_timer_sh command listaddons) $OPTS";;
            *)  case "$cur" in
                    +*) completions=$(eval TIMERTXT_VERBOSE=0 $_timer_sh command listproj)
                        COMPREPLY=( $( compgen -W "$completions" -- $cur ))
                        [ ${#COMPREPLY[@]} -gt 0 ] && return 0
                        # Fall back to projects extracted from done tasks.
                        completions=$(eval 'TIMERTXT_VERBOSE=0 TIMERTXT_SOURCEVAR=\$DONE_FILE' $_timer_sh command listproj)
                        ;;
                    @*) completions=$(eval TIMERTXT_VERBOSE=0 $_timer_sh command listcon)
                        COMPREPLY=( $( compgen -W "$completions" -- $cur ))
                        [ ${#COMPREPLY[@]} -gt 0 ] && return 0
                        # Fall back to contexts extracted from done tasks.
                        completions=$(eval 'TIMERTXT_VERBOSE=0 TIMERTXT_SOURCEVAR=\$DONE_FILE' $_timer_sh command listcon)
                        ;;
                    *)  if [[ "$cur" =~ ^[0-9]+$ ]]; then
                            # Remove the (padded) task number; we prepend the
                            # user-provided $cur instead.
                            # Remove the timestamp prepended by the -t option,
                            # and the done date (for done tasks); there's no
                            # timer.txt option for that yet.
                            # But keep priority and "x"; they're short and may
                            # provide useful context.
                            # Remove any trailing whitespace; the Bash
                            # completion inserts a trailing space itself.
                            # Finally, limit the output to a single line just as
                            # a safety check of the ls action output.
                            local timer=$( \
                                eval TIMERTXT_VERBOSE=0 $_timer_sh '-@ -+ -p -x command ls "^ *${cur} "' | \
                                sed -e 's/^ *[0-9]\{1,\} //' -e 's/\((.) \)[0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} /\1/' \
                                    -e 's/\([xX] \)\([0-9]\{2,4\}-[0-9]\{2\}-[0-9]\{2\} \)\{1,2\}/\1/' \
                                    -e 's/[[:space:]]*$//' \
                                    -e '1q' \
                            )
                            # Append task text as a shell comment. This
                            # completion can be a safety check before a
                            # destructive timer.txt operation.
                            [ "$timer" ] && COMPREPLY[0]="$cur # $timer"
                            return 0
                        else
                            return 0
                        fi
                        ;;
                esac
                ;;
        esac
    fi

    COMPREPLY=( $( compgen -W "$completions" -- $cur ))
    return 0
}
complete -F _timer timer.sh

# If you define an alias (e.g. "t") to timer.sh, you need to explicitly enable
# completion for it, too:
#complete -F _timer t

# If you have renamed the timer.sh executable, or if it is not accessible through
# PATH, you need to add and use a wrapper completion function, like this:
#_timerElsewhere()
#{
#    local _timer_sh='/path/to/timer2.sh'
#    _timer "$@"
#}
#complete -F _timerElsewhere /path/to/timer2.sh

# If you use aliases to use different configuration(s), you need to add and use
# a wrapper completion function for each configuration if you want to complete
# fron the actual configured task locations:
#alias timer2='timer.sh -d "$HOME/timer2.cfg"'
#_timer2()
#{
#    local _timer_sh='timer.sh -d "$HOME/timer2.cfg"'
#    _timer "$@"
#}
#complete -F _timer2 timer2
